# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: the Light moved through the hazy
subtitle: 透雾之光
keywords: IC, 人文
description: 
author: John Wang
language:
    - zh-cn
    - en

timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: https://shuoit.net
url: https://127.0.0.1
root: /
permalink: :category/:entitle-:timestamp.html
permalink_defaults:
  lang: en

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - README.zhCN.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link.enable: false # Open external links in new tab
filename_case: 0s
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: 技术
category_map:
   技术: tech
   人文: human
   存疑: research
tag_map:
  dart: dart
  swift: swift
  objective-c: oc
  java: java
  python: py
  javascript: js
  typescript: ts
  苹果: ios
  安卓: android
  麦克: mac
  webx: web
  vue2: vue2
  vue3: vue3
  react: react
  flutter: flutter
  react-native: rn
  hexo: hexo
  后端: back-end
  前端: front-end
  跨端: cross-app
  读书: reading
  旅行: traveling
  配置: configs
  码常规: dev-tips
  黑科技: cool-tech
  碎碎念: impression
  生产力: productivity


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/


theme: jsimple
#theme: hexo-theme-hipaper

# Configuration for search module: hexo-generator-search 
search:
  path: search.json
  field: all
  content: true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  #repo: https://tangkunyin@github.com/shuoit/shuoit.github.com.git
  repo: https://wangbo-john@github.com/wangbo-john/blog.git
  branch: master

# Backup settings see:https://github.com/coneycode/hexo-git-backup
backup:
  type: git
  message: backup my blog of https://wangbo-john.github.io
  repository:
    github: https://github.com/wangbo-john/blog.git,master

lazyload:
  enable: true
  onlypost: false # optional 
  loadingImg: # optional eg ./images/loading.gif 
  isSPA: false # optional
