# site name
site_name: the Light moved through the hazy
short_name: 透雾之光

# Master info. It won't work if the one from (author|authorLink|avatar|authorDesc) be written in post.md
webmaster:
  name: 王波
  avatar: /images/favicon.png
  home: https://wangbo-john.github.io
  desc: 一个迷之自信的老工程师（不是《脱口秀大会》杨笠吐槽的那种哦）

# CSP Mode, true means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
csp_enable: true

# Read Mode. day or night
read_mode: day

# favicon
favicon: /images/favicon.png
# unique avatar
avatar_show: false
avatar_image: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
home_page_sort: -1
# Home page article shown number
home_article_shown: 10

# Post sticky top support (you need to set top:number in post.md. )
sticky_top:
  enable: true

# your site build time or domain buy time
site_building_time: 12/25/2020

# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   技术: tech
   人文: human
   存疑: research

# Customize left navigation menus. faName is FontAwesome style name
left_nav_menus:
- uri: help
  title: 帮助
  faName: fa-question-circle


# cover info config
cover_title: 交流、探讨 技术、人文 之 美
cover_description: 美


# sns url
sns:
  github: https://github.com/wangbo-john
  #twitter: https://twitter.com/tangkunyin
  #weibo: https://weibo.com/tangkunyin
  #instagram: https://www.instagram.com/mtangsir/



# article declare. default content in languages
post_declare: true

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## Analytics setting. Google default
analytics:
  enable: true
  google_analytics_id: UA-131527701-1

## Google AdSense.
adsense:
  enable: true
  auto: true
  client_id: ca-pub-4837253996935841
  page_tb_id: 3228829614
  archive_id: 2266978027
  tags_id: 5073050868
  post_inner_id: 9087656062
  post_left_id: 1712444257
  post_right_id: 6857083436


## Comments settings. Disqus
##                  | Gitment（Introduction: https://imsun.net/posts/gitment-introduction/）
##                  | gitalk  (Official website: https://gitalk.github.io/)
comments:
  enable: false
  disqus_shortname:
  gitment:
    repo:
    githubID:
    ClientID:
    ClientSecret:
    lazy: true
  gitalk:
    on: true
    owner: xx
    repo: xx.github.io
    admin: ['xxx']
    clientID:
    clientSecret:

# Git-pages server info (Coding Pages|Github Pages)
server_name:
server_url:

mathjax:
   enable: true

## Baidu ziyuan auto-commit. see https://ziyuan.baidu.com/
baidu_auto_push: true


post_asset_folder: true
